### ISSUE TITLE
How to make the public sync-node?

### ISSUE THREAD

**Issue by username1565** [username1565/signatum-source#1]
How to make the public sync-node? See instructions here!

**Comment by Blinki1** [comment]
Hello, can you tell me how to setup a new Node?

**Comment by username1565** [comment]
To make your own public sync-node, follow this instructions:
1. Run your wallet as server. (see next info)
2. Make your port on external IP - opened, using port-forwarding for default port 33333.
3. Check port online. (see next info, if IP dynamic, or if you using the domain name)
 - go here: https://ping.eu/port-chk/
 - enter your IP and default port 33333.
 - press button
 - Status may be **open**

____________________________________________
To run your wallet as server, config file signatum.conf may contains this strings:
```
#For sync-node this can be added only
#do port-forwarding if you have NAT
#and check the port online for your external IP

#by default staking=1 if this not specified, but I comment this and redefine this
#staking=1

#Now default
staking=0
#because no need to confirm transactions when someone else have enable staking.
#I see active connections and blockchain height is growing, so POS-miners exists in the mainnet.
#But POS rewards so low, and blockchain height growing if staking will be enable for me.
#POS percentage is 5% per year and this rewards I can get after next once POS staking,
#even if my coins will be unspent long time.
#so staking is disabled now.

#enable daemon
daemon=1

#listen cliens who want to open incoming connections
listen=1
#on localhost
bind=127.0.0.1
#listen on all addresses (local, LAN, external IP)
bind=0.0.0.0
#lisen on this default port
port=33333

#addnode-list
addnode=node.611.to:33333
addnode=77.93.110.194:33333
addnode=80.76.235.194:33333
addnode=46.163.165.175:33333
addnode=77.93.110.194:63046
addnode=46.163.165.175:63875
addnode=185.202.137.251:60209
#here will be checking the default port 33333
addnode=coinsmarkets.com
addnode=novaexchange.com
addnode=yobit.net
addnode=47.184.192.237
addnode=31.193.131.89
addnode=147.135.220.159
addnode=136.243.50.159
addnode=80.6.164.72
addnode=129.242.71.138
addnode=195.122.243.226
addnode=45.77.235.89
#addnode=ANOTHER_PUBLIC_SYNCNODES:33333
#addnode=ANOTHER_PUBLIC_SYNCNODES:33333
#addnode=ANOTHER_PUBLIC_SYNCNODES:33333
#etc...
```
See [big addnode list with nodes here](https://github.com/username1565/signatum-source/blob/master/README.md).
____________________________________
If your don't see port opened after check port, unlock Internet activity
for signatum program in your firewalls.
____________________________________
If your have port opened, anyone can connect to your sync-node
by adding this string in signatum.conf:
```addnode=YOUR_EXTERNAL_IP:33333```
Then, if you have full blockchain, anyone can synchronize wallet from your sync-node.

If you have dynamic IP, you can using DDNS services, like https://www.duckdns.org/
and then, you sync node can have the domain name.
For example: ```addnode=your_username.duckdns.org:33333```
Also, in this case, you can check port, using this domain name on the site https://ping.eu/port-chk/
As you can see here: https://www.duckdns.org/spec.jsp
the dynamic IP address can be updated for domain name, from browser, using url:
https://duckdns.org/update/{YOURDOMAIN}/{YOURTOKEN}[/{YOURIPADDRESS}]
but, you can using next url:
https://duckdns.org/update/{YOURDOMAIN}/{YOURTOKEN}
and in this case IP will be updated for your external IP.
This page is static, and not contains dynamic data,
and you can add this just as the favorite tab for your browser.
_____________________________________
After you make your own sync-node, tell me the address
and I will add this to my signatum.conf
Also, we can test this node together.
For example, I can connect to you with blockchain as client, and you will see the syncronization.
_____________________________________
Best regards.

**Comment by Blinki1** [comment]
Hello, thx for the Answer, i will install Signatum Wallet on a seperat PC an make sure the Port is open. The i will send you the adress.

**Comment by username1565** [comment]
@Blinki1, I see on reddit, you have fails with binding.
Maybe signatum internet activity is just dissallowed in your firewall.

**Comment by Blinki1** [comment]
Hello the fails withe binding i have solved

**Comment by Blinki1** [comment]
is SIGT on a Exchange?

**Comment by username1565** [comment]
@Blinki1
https://yobit.net/ru/trade/SIGT/BTC
https://yobit.net/ru/trade/SIGT/ETH
https://yobit.net/ru/trade/SIGT/DOGE
https://yobit.net/ru/trade/SIGT/WAVES
https://yobit.net/ru/trade/SIGT/USD
https://yobit.net/ru/trade/SIGT/RUR

**Comment by Blinki1** [comment]
To day 1 Trade with 3000 SIGT :-)

**Comment by username1565** [comment]
@Blinki1. Because mainnet is unstable!
Did you saw [signatumd page](https://github.com/signatumd/source)?
OMG...

**Comment by Blinki1** [comment]
Now, i have mined some coin an then all the coins are usles wallet is out of Sync.
What is your part now with SIGT?

**Comment by username1565** [comment]
@Blinki1
Just, I did fork the signatum source code,
made the sync-node,
and want to just hold, my mined signatums, up to 150 years!
But... In the working mainnet!

And I cann't setup my own [iquidus block explorer](https://github.com/iquidus/explorer) for windows.
WTF? I did mining signatum - all summer 2017 (over 90 days)!
I did this on sigt.suprnova.cc, with many miners, with high difficulty and net hashrate.
And what I see? 12 satoshies?? No-no...

**Comment by Blinki1** [comment]
hehe exactly the same for me, I also mined at sigt.suprnova.cc and got nothing out.

**Comment by username1565** [comment]
@Blinki1 but now, no one cann't do POW-mining signatum.
Console command ```getinfo``` says about
the total available supply is 137.5 million coins.
And only POS mining.
Total available peoples in the World is 7.5 billions,
so 137500000 [SIGT] / 7500000000 [peoples] = 0.01833333 [SIGT/for each human, for all life].
Hehhehheh.

**Comment by Blinki1** [comment]
I go to bed an my pc have to sync the Wallet, tomorrow i will setup a new PC for using the Wallet as Server.

**Comment by username1565** [comment]
@Blinki1, ok. Tell me the IP:port or domain_name:port tomorrow.

**Comment by Blinki1** [comment]
I have setup the new PC withe the Wallet an all is Sync.
My adress is biehl.selfhost.me:33333

**Comment by username1565** [comment]
@Blinki1, your node added to my signatum.conf and [here](https://github.com/username1565/signatum-source/blob/master/README.md).

But this seems like not working sync-node...
**How many active connections do you have?**

I did run this command ```Win+R -> cmd -> nslookup biehl.selfhost.me```
and I see the IP of your node there.
Also, I did write in signatum wallet
this console comand: ```getpeerinfo```,
and I see that is my node not connected to your IP,
but you connected to my node as client connected to the server.
I don't see your domain name in ```getpeerinfo```-response,
but I see your IP, and you have connected with different port.

I did check port 33333 for your node, here: https://ping.eu/port-chk/
and I see port have status **open**,
but I cann't connect to ```biehl.selfhost.me:33333``` as client,
using in signatum.conf the commands ```addnode=``` or ```connect=```.

You can test connections yourself, using different data-directory
and signatum-client.conf, for example, ```start-signatum.bat``` can contains this parameters:
```signatum-qt.exe -datadir=signatum_client_data -conf=signatum-client.conf```
and near signatum-qt.exe you can create the folder "signatum_client_data",
then create inside this folder ```signatum-client.conf```,
and add this there:
```
#just disable staking
staking=0

#"addnode="
#default port on localhost
#addnode=127.0.0.1
#addnode=0.0.0.0
#addnode=your_IP
#addnode=biehl.selfhost.me

#specified port 33333
#addnode=127.0.0.1:33333
#addnode=0.0.0.0:33333
#addnode=YOUR_IP:33333
#addnode=biehl.selfhost.me:33333

#"connect="
#	by IP
#addnode=127.0.0.1
#addnode=0.0.0.0
#addnode=your_IP
#addnode=biehl.selfhost.me

#	IP:PORT
#addnode=127.0.0.1:33333
#addnode=0.0.0.0:33333
#addnode=YOUR_IP:33333
#addnode=biehl.selfhost.me:33333
```
Then, you can start signatum wallet as client, with next parameters:
```signatum-qt.exe -data-dir=new_data_folder -conf=signatum_client.conf```
using double-click on ```start_signatum.bat```, even if your node runned.

So, as you see, you can test yourself
the connections to your node as client,
using in signatum-client.conf next commands: ```addnode=``` or ```connect=```
and using this IP addresses: ```127.0.0.1:33333```, ```0.0.0.0:33333```,
```YOUR_IP:33333```, ```biehl.selfhost.me:33333```.

I think, you can connect yourself with:
```
addnode=127.0.0.1:33333
addnode=0.0.0.0:33333
connect=127.0.0.1:33333
connect=0.0.0.0:33333
```
BUT NOT TO:
```
addnode=YOUR_IP:33333
addnode=biehl.selfhost.me:33333
connect=YOUR_IP:33333
connect=biehl.selfhost.me:33333
```
Because I cann't connect.

I did try to run new signatum wallet as client too,
by just adding to my new signatum_client.conf the following strings:
```
addnode=biehl.selfhost.me
addnode=biehl.selfhost.me:33333
addnode=IP_FROM_NSLOOKUP
addnode=IP_FROM_NSLOOKUP:33333
#and no any connections...

#then I did add this strings, using "connect="
connect=biehl.selfhost.me
connect=biehl.selfhost.me:33333
connect=IP_FROM_NSLOOKUP
connect=IP_FROM_NSLOOKUP:33333
#and no any connections

#	only this working for me, because I have runned my node on localhost
#addnode=127.0.0.1:33333
#	or
#connect=127.0.0.1:33333
#in this case syncronization working on client, after connecting
```
And, as you can see, I cann't connect to ```biehl.selfhost.me:33333``` or ```biehl.selfhost.me:33333```
Maybe your firewall or brandmauer is blocking the incoming connections.

As I said earlier, I see you have connected to my node as client, and with different port.
I see the port is opened, but I cann't connect to the port 33333 as client.
That means, maybe your firewall is blocking incoming connections for signatum program.

Play with commenting/uncommenting this string, using "#", in signatum.conf,
and check your firewall, because I cann't connect as client.

**Comment by Blinki1** [comment]
@username1565 I think now it looks good:

I have 12 Connections

this is getpeerinfo from a other Client.

  | [{"addr" : "biehl.selfhost.me",
"addrlocal" : "77.176.61.117:57105",
"services" : "00000001",
"lastsend" : 1541927115,
"lastrecv" : 1541927117,
"bytessent" : 1351
,"bytesrecv" : 814,
"conntime" : 1541927115,
"timeoffset" : -2,
"pingtime" : 0.05986600,
"version" : 70000,
"subver" : "/Signatum:1.0.0/
","inbound" : false,
"startingheight" : 656062,
"banscore" : 0,
"**syncnode" : true},**

{"addr" : "biehl.selfhost.me:33333
","addrlocal" : "77.176.61.117:57106"
,"services" : "00000001"
,"lastsend" : 1541927115,
"lastrecv" : 1541927117,
"bytessent" : 298,
"bytesrecv" : 1381,
"conntime" : 1541927115,
"timeoffset" : -2,
"pingtime" : 0.06083700,
"version" : 70000,
"subver" : "/Signatum:1.0.0/",
"inbound" : false,
"startingheight" : 656062,
"banscore" : 0,
"syncnode" : false}

**Comment by username1565** [comment]
@Blinki1, You are on windows?

**Comment by Blinki1** [comment]
@username1565  yes
can you now connect?

**Comment by username1565** [comment]
@Blinki1 No, I cann't. I cann't connect as client even to my node by domain name or external IP.
Only using 127.0.0.1 or 0.0.0.0 I see active connection.
Maybe I have some problem on my side, because I see you connect using your external addresses.

**Comment by Blinki1** [comment]
Yes i have installt the wallet on a other PC and in the adress List i have my external link.
on the pc where the Wallet run as sync-node i have the incomming connection.

**Comment by username1565** [comment]
Ok. I close this issue then. If you have some questions open next issue.
Have a nice day.

**Comment by Blinki1** [comment]
Hello, you can delete my Adress, ih have sell all mit SIGT

**Comment by username1565** [comment]
Ok, @Blinki1, [your node was been deleted](https://github.com/username1565/signatum-source/commit/c9adb63e61401c5ebf98a787748d32ff0a3fadae).
